# Production-like environment overlay for local testing
# Usage: docker compose -f compose.yaml -f compose.production.yaml up -d

services:
    truetrack-prod:
        build:
            context: .
            dockerfile: Dockerfile.production
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'truetrack:production'
        container_name: truetrack-prod
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            APP_ENV: production
            APP_DEBUG: false
            SESSION_DRIVER: redis
            CACHE_DRIVER: redis
            QUEUE_CONNECTION: redis
        volumes:
            - './storage:/var/www/html/storage'
            - './bootstrap/cache:/var/www/html/bootstrap/cache'
            - 'truetrack-build-assets:/var/www/html/public/build'
        networks:
            - sail-prod
        depends_on:
            - pgsql-prod
            - redis-prod
        healthcheck:
            test: ["CMD", "php", "artisan", "health:check"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    nginx-prod:
        image: 'nginx:alpine'
        container_name: truetrack-nginx-prod
        ports:
            - '${PROD_APP_PORT:-8080}:80'
        volumes:
            - './nginx/production.conf:/etc/nginx/conf.d/default.conf:ro'
            - './public:/var/www/html/public:ro'
            - 'truetrack-build-assets:/var/www/html/public/build:ro'
            - './storage/app/public:/var/www/html/storage/app/public:ro'
        networks:
            - sail-prod
        depends_on:
            - truetrack-prod
        healthcheck:
            test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
            interval: 30s
            timeout: 10s
            retries: 3

    pgsql-prod:
        image: 'postgres:18-alpine'
        container_name: truetrack-postgres-prod
        ports:
            - '${PROD_DB_PORT:-5433}:5432'
        environment:
            PGPASSWORD: '${PROD_DB_PASSWORD:-secret}'
            POSTGRES_DB: '${PROD_DB_DATABASE:-truetrack_prod}'
            POSTGRES_USER: '${PROD_DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${PROD_DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql-prod:/var/lib/postgresql/data'
        networks:
            - sail-prod
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${PROD_DB_DATABASE:-truetrack_prod}'
                - '-U'
                - '${PROD_DB_USERNAME:-sail}'
            retries: 3
            timeout: 5s

    redis-prod:
        image: 'redis:7-alpine'
        container_name: truetrack-redis-prod
        ports:
            - '${PROD_REDIS_PORT:-6380}:6379'
        volumes:
            - 'sail-redis-prod:/data'
        networks:
            - sail-prod
        command: redis-server --appendonly yes --appendfsync everysec
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    queue-worker-prod:
        build:
            context: .
            dockerfile: Dockerfile.production
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'truetrack:production'
        container_name: truetrack-queue-prod
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            APP_ENV: production
            APP_DEBUG: false
            CONTAINER_ROLE: queue
        volumes:
            - './storage:/var/www/html/storage'
            - './bootstrap/cache:/var/www/html/bootstrap/cache'
        networks:
            - sail-prod
        depends_on:
            - pgsql-prod
            - redis-prod
        command: php artisan queue:work redis --queue=default --tries=3 --timeout=300 --sleep=3
        restart: unless-stopped

    scheduler-prod:
        build:
            context: .
            dockerfile: Dockerfile.production
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'truetrack:production'
        container_name: truetrack-scheduler-prod
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            APP_ENV: production
            APP_DEBUG: false
            CONTAINER_ROLE: scheduler
        volumes:
            - './storage:/var/www/html/storage'
            - './bootstrap/cache:/var/www/html/bootstrap/cache'
        networks:
            - sail-prod
        depends_on:
            - pgsql-prod
            - redis-prod
        command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction && sleep 60; done"
        restart: unless-stopped

networks:
    sail-prod:
        driver: bridge
        name: truetrack-production

volumes:
    sail-pgsql-prod:
        driver: local
        name: truetrack-postgres-prod-data
    sail-redis-prod:
        driver: local
        name: truetrack-redis-prod-data
    truetrack-build-assets:
        driver: local
        name: truetrack-build-assets
